the Alignments and fleed correction
octangrp/ad-summum pull request #29
Opened 2020-04-21 07:15 UTC by Landos007

2020-04-21 07:21 UTC, musayann requested changes

2020-04-21 07:21 UTC, musayann commented on src/components/sections/information.js
> +import { Link } from "gatsby"
I thought this page had to be removed

2020-04-21 07:21 UTC, musayann commented on src/pages/page-2.js
> +const SecondPage = () => (
Please delete this page

2020-04-21 07:25 UTC, musayann commented
@Landos007 Please capitalize the PR's title

2020-04-21 07:48 UTC, Landos007 commented on src/components/sections/information.js
> +import { Link } from "gatsby"
which one?

2020-04-21 07:48 UTC, Landos007 commented on src/components/sections/information.js
> +import { Link } from "gatsby"
the member.js?

2020-04-21 07:50 UTC, Landos007 commented on src/components/sections/information.js
> +import { Link } from "gatsby"
or information.js

2020-04-22 07:31 UTC, musayann approved these changes

2020-04-22 07:38 UTC, merged